[GLOBAL]
pants_version = "2.14.0"
backend_packages = [
  "pants.backend.python",
]

[python]
interpreter_constraints = ["CPython==3.9.5"]

[python-infer]
unowned_dependency_behavior = "error"

[anonymous-telemetry]
enabled = false