[GLOBAL]
pants_version = "2.6.1rc1"
print_stacktrace = true
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.pylint"
]

[python-setup]
interpreter_constraints = ["CPython==3.9.*"]
