[GLOBAL]
pants_version = "2.5.1rc3"
print_stacktrace = true
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.isort",
  "custom_autoflake",
  "custom_black",
  "custom_flake8",
  "import_fixer",
]
plugins = [
  "autoflake>=1.4",
]

pants_ignore.add = [
  "/.*"
]

ignore_warnings = [
  "$regex$DeprecationWarning: invalid escape sequence",
  "$regex$FutureWarning: Possible set union at position"
]


[source]
root_patterns = [
  "/app",
  "/pants-plugins"
]

[autoflake]
args = ["--remove-all-unused-imports"]

[python-infer]
inits = true
string_imports = true

[dependees]
transitive = true
closed = true

[black]
version = "black==21.5b1"

[anonymous-telemetry]
enabled = false
