[GLOBAL]
pants_version = "2.5.0"
print_stacktrace = true
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  "pants.backend.python",
  "custom_black",
  "custom_flake8",
  "wildcard_imports"
]

pants_ignore.add = [
  "/.*"
]

[source]
root_patterns = [
  "/app",
  "/pants-plugins"
]

[python-infer]
inits = true
string_imports = true

[dependees]
transitive = true
closed = true

[black]
config = "pyproject.toml"
version = "black==21.5b1"

[flake8]
config = "setup.cfg"

[anonymous-telemetry]
enabled = false
