[GLOBAL]
pants_version = "2.5.0"
print_stacktrace = true
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  "pants.backend.python",
  "write_read"
]

pants_ignore.add = [
  "/.*",
  "/*.py"
]

[source]
root_patterns = [
  "/app",
  "/pants-plugins"
]

[python-infer]
inits = true
string_imports = true

[dependees]
transitive = true
closed = true

[anonymous-telemetry]
enabled = false
