[GLOBAL]
pants_version = "2.3.0rc2"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.mixed_interpreter_constraints"
]

[python-setup]
interpreter_constraints = ["CPython==2.7.*"]
