[GLOBAL]
pants_version = "2.14.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  "pants.backend.plugin_development",
  "pants.backend.python",
  "changer"
]

[python]
interpreter_constraints = ["CPython==3.9.5"]

[python-infer]
unowned_dependency_behavior = "error"

[anonymous-telemetry]
enabled = false