[GLOBAL]
pants_version = "2.10.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  "pants.backend.python",
  "pants.backend.experimental.python.lint.autoflake",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.typecheck.mypy",
  "build_file_defaults",
]
use_deprecated_python_macros = false

[source]
root_patterns = [
  "/",
  "pants-plugins",
]

[python]
interpreter_constraints = ["CPython==3.9.5"]

[build-file-defaults]
build_defaults = """
{
  "app/module_1": {
    "python_sources": ("skip_black=True", "skip_isort=False",)
  },
  "app/module_2": {
    "python_sources": ("skip_black=True", "skip_isort=True",),
    "python_tests": ("skip_black=False", "skip_isort=False", "skip_flake8=False",)
  },
}
"""

[anonymous-telemetry]
enabled = false
