[GLOBAL]
pants_version = "2.8.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.flake8",
  "custom_infer",
]

[python]
interpreter_constraints = ["CPython>=3.7,<3.10"]

[dependees]
transitive = false
closed = true

[python-infer]
imports = false
inits = false

[anonymous-telemetry]
enabled = false
