[GLOBAL]
pants_version = "2.17.0rc1"
backend_packages = [
  "pants.backend.python",
]

[source]
root_patterns = [
  "/app",
]


[python]
interpreter_constraints = ["CPython==3.9.5"]

[python-infer]
use_rust_parser = true
unowned_dependency_behavior = "error"
ambiguity_resolution = "by_source_root"

[anonymous-telemetry]
enabled = false