[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pants-example"
version = "0.1.0"
description = "Pants example repo"
authors = ["Nick Grisafi <njgrisafi@gmail.com>"]
readme = "README.md"
repository = "https://github.com/njgrisafi/pants-example"
packages = [
    {include = "app"}
]

[tool.poetry.dependencies]
python = ">=3.7,<3.9"


[tool.poetry.dev-dependencies]
pytest = "3.1.1"
"pantsbuild.pants" = "2.5.0"
black = {version = "^21.5b1", allow-prereleases = true}
flake8 = "^3.9.2"
autoflake = "^1.4"

[tool.black]
line-length = 120
fast = true

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
