[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pants-example"
version = "0.1.0"
description = "Pants example repo"
authors = ["Nick Grisafi <njgrisafi@gmail.com>"]
readme = "README.md"
repository = "https://github.com/njgrisafi/pants-example"
packages = [
    {include = "app"}
]

[tool.poetry.dependencies]
python = "^3.9"
requests = {git = "ssh://git@github.com/psf/requests", rev = "b0e025ade7ed30ed53ab61f542779af7e024932e"}

[tool.poetry.dev-dependencies]
pytest = "3.1.1"

[subprocess-environment]
env_vars.add = [
  "SSH_AUTH_SOCK",
]

[anonymous-telemetry]
enabled = false