# python_library(sources=["!another.py", "*.py"], dependencies=[":another"])
# python_library(sources=["!another.py", "*.py"])
# python_library(sources=["!another.py", "*.py"], tags=["skip-import-infer"])
# python_library(sources=["!another.py", "*.py"], skip_self_import_infer=True)
# python_library(sources=["!another.py", "*.py"], skip_external_import_infer=True)


# python_library(name="another", sources=["another.py"])
python_sources()
