python_sources(
    name="file_1",
    sources=["file_1.py", "file_2.py"],
    skip_black=True,
    skip_isort=True,
)

python_sources(
    name="file_2",
    sources=["file_2.py"],
    skip_black=True,
    skip_isort=True,
)

python_tests(
    name="Test",
    sources=["example.py"],
    skip_black=False,
    skip_isort=False,
    skip_flake8=False,
)
